### ISSUE TITLE
Review 2018-06-11-perceptron.md

### ISSUE THREAD

**Issue by gachiemchiep** [dlapplications/dlapplications.github.io#1]
Hello @hitogen                        

Trao đổi, review bài viết ở trong này nhé .

Bài viết ở : https://dlapplications.github.io/2018-06-11-perceptron/ 

Commit mới nhất ở đây nhỉ. 
e3b62a8fee8c512d4a17856a420bf587a2c2be48

Cố gắng tránh việc merge các branch lại nhé. 
Merge dữ quá sau này tìm lại log không được đâu.

**Comment by hitogen** [comment]
dạ ok ạ. Mới xài nên còn nhiều bỡ ngỡ, đại ca thông cảm :)

**Comment by gachiemchiep** [comment]
@hitogen 

Từ từ rồi quen thôi. Hồi xưa a còn không biết xài
