### ISSUE TITLE
[writing] transfer learning với tensorflow

### ISSUE THREAD

**Issue by ducanh841988** [dlapplications/dlapplications.github.io#12]
Bài này mình sẽ cùng em Đăng viết. Mình để lên đây trước cho mọi người cùng biết. Bài này là task challenge của em ấy để được join vào nhóm nhe!

**Comment by hitogen** [comment]
@ducanh841988  bai nay bao gio deadline vay dai ca?

**Comment by ducanh841988** [comment]
15/7 nhé

**Comment by ducanh841988** [comment]
Day la link de moi nguoi review nhe. Em ay chua dua hinh nen minh se post sau.

https://dlapplications.github.io/2018-07-15-Transfer-Learning-Basic/

**Comment by hitogen** [comment]
@HaiDang2001VN  bài cũng tương đối dài nên a cũng chưa đọc kĩ hết được nhưng có một số gop ý như sau:
1. Cách sắp xếp bố cục: 
A chưa hiểu lắm về ý đồ e bố trí các phần nhưng a thấy đọc hơi rối một chút.
(i) Theo a nghĩ thì nên đưa phần 4.1 cơ sở ra trc để từ đó lý giải những lợi ích ở phần 3 và hạn chế ở phần 5.2. 
(ii) Ở phần 2.3 e phân ra "sự cần thiết" và "chính thức" là có ý đồ gì vậy? Cá nhân a thì a thấy nếu gộp phần 2.3 sự cần thiết với phần 5.3 ý tưởng để làm mở bài thì người đọc sẽ hiểu ngay từ đầu về ý tưởng và tại sao nên dùng transfer learning nên sẽ dễ follow bài viết hơn.

2. Cách dùng từ ngữ: 
(i) E nên giải thích từng thuật ngữ chứ không nên để chung như phần 4.1 là "Feature Engineering (Feature Extractor/Hand-crafted Features)". Ví dụ có thể viết thế này: 
"Feature Engineering là quá trình dựa trên những hiểu biết của con người về vấn đề cần giải quyết (domain knowledge) để từ đó rút ra những đặc trưng (feature) của data có thể giúp ích cho việc giải quyết vấn đề đó. Do đó các feature này được gọi là hand-crafted feature (nôm na là làm thủ công). Feature extractor là chỉ model dùng để trích xuất ra feature nói chung." 
(ii) Tiếp theo, Classifier/Regressor: nên viết chung chung là sau đó sẽ dùng các model để phân loại hoặc dự đoán kết quả từ các feature trên thay vì chỉ đề cập đến SVM và Random Forest không thôi.
(iii) Trong phần sau của 4.1 nếu có thể thì nói sơ qua tại sao DL có thể extract useful feature một cách tự động và tại sao kết hợp 2 stage lại thì đạt đc kết quả cao hơn là tách biệt thì tốt.
(iv) E có thể giải nghĩa rõ hơn một chút "fine tuning" là gì ko?

**Comment by HaiDang2001VN** [comment]
Dạ cảm ơn anh @hitogen  đã review giúp em ạ, em đã chỉnh sửa và upload lên lại rồi, mong anh tiếp tục giúp đỡ ạ.
_______________________________________________________________________________________________________
Task control:
- [ ] Task 1 : [Lý thuyết](https://dlapplications.github.io/2018-07-15-Transfer-Learning-Basic/) (In Review)
- [ ] Task 2 : Thực hành (In Progress)

**Comment by hitogen** [comment]
@HaiDang2001VN  Thanks e, a thấy dễ follow bài viết hơn rất nhiều rồi. Chỉ có một góp ý nhỏ nữa ở phần 4.1 e dùng header a, b để đánh số nhưng a thấy font nó nhỏ quá (có khi nhỏ hơn cả chữ thường trong bài) nên thấy tổng thể ko cân đối lắm. E thử dùng gạch đầu dòng xem nó có dễ nhìn hơn ko. Ví dụ:
+ Lợi ích: ....
+ Hạn chế: ....

**Comment by HaiDang2001VN** [comment]
Dạ cảm ơn anh ạ, em đã gạch đầu dòng và tab phần nội dung vào cho vừa cột rồi ạ. Có vấn đề gì còn cần phải chỉnh sửa không ạ?
Cảm ơn anh @hitogen  ạ.

**Comment by hitogen** [comment]
@HaiDang2001VN công nhận e viết nhanh thật, a thì thấy ok rồi. Đại ca @gachiemchiep thấy ok chưa ạ?

**Comment by ducanh841988** [comment]
Anh cũng thấy ok. Mọi người nghĩ sao nếu mình làm một từ điển Anh Việt các cụm từ thường dùng trong deep learning?

**Comment by hitogen** [comment]
Cũng hay ạ. E thấy có thể tham khảo cái này http://www.wildml.com/deep-learning-glossary/
