### ISSUE TITLE
Number plate detection

### ISSUE THREAD

**Issue by ducanh841988** [dlapplications/dlapplications.github.io#13]
Cái này như bàn ở bên kia. Mình sẽ sử dụng image processing đơn giản đề làm. Mặc dù kết quả có thể không được cao nhưng ở mức độ tutorial mình nghĩ là chấp nhận được. Bài này mình set deadline 15/7

**Comment by ducanh841988** [comment]
https://github.com/dlapplications/dlapplications.github.io/blob/master/_posts/2018-7-6LicencePlaceDetection.md

Mọi người review nhé.

**Comment by hitogen** [comment]
@ducanh841988  E nghĩ nên để phần code của từng bước gần phần thuyết minh thì sẽ dễ theo dõi hơn.
Bài này chưa liên quan tới DL nên e nghĩ nên có thêm phần mở bài vì sao không xài DL vì page mình là hướng tới giới thiệu về DL.

**Comment by ducanh841988** [comment]
Cái code a để chung cho dễ hiểu và dễ copy. Em cho vài lý do để anh dễ viết!

**Comment by hitogen** [comment]
Vì nếu là e thì e sẽ muốn vừa đọc vừa làm theo code, chứ nếu code ở dưới hết thì vừa phải kéo lên kéo xuống để xem phần giải thích là của phần code nào.

**Comment by gachiemchiep** [comment]
@ducanh841988 

Tôi có 3 comment 

1. Nên tách phần cài đặt software khỏi phần 2 , đưa vào phần riêng
2.  Code chạy đến đâu thì đưa hình ảnh đến đó sẽ dễ hiểu hơn.
3. Ở những ví dụ thất bại,  nên thêm phần dùng cách nào để khắc phục ?

**Comment by ducanh841988** [comment]
Mọi người vào review lại nhé. Đã sửa rồi ah

**Comment by hitogen** [comment]
@ducanh841988  e có một số ý kiến thế này:
1. Phần mở đầu chỗ liệt kê các bước e nghĩ nên để thành bullet list hay đánh số thay vì chỉ để header để cho người ta dễ thấy là mình đang liệt kê.
2. Phần 3, chỗ xử lý ảnh dùng pp này kia (vd: iterative bilateral filter, canny...) thì nếu mình không giải thích thì e nghĩ nên để link sẵn để người chưa biết có thể tham khảo nhanh.
3. Chỗ code có vòng lặp for thì nên bỏ vào  cả đoạn code block vào giữa ``` chứ format từng dòng code thế nó mất hết indentation.
4. Cuối phần 4 có câu kết "Nếu các bạn muốn khắc phục các nhược điểm trên, mình khuyên nên tìm hiểu object detection trong deep learning". Mục đích của page là giới thiệu DL và cách để ứng dụng mà bài viết lại giới thiệu một ứng dụng ko dùng DL rồi khuyên người đọc đi tìm hiểu thêm DL thì e thấy nó không được ổn :)). Đọc đến cuối đang chờ câu đại ý là "Để khắc phục các nhược điểm chúng ta có thể dùng object detection trong DL và nhóm sẽ giới thiệu trong các bài viết tới" thì gặp ngay câu kết trên nên hơi hụt hẫng. 
Tạm thời e có mấy ý kiến cá nhân như trên ạ.

**Comment by dl-applications** [comment]
@hitogen Thank em. Đúng là có người review thì bài sẽ rất dễ hiểu, nhìn từ nhiều khía cạnh. Anh đã sửa lại nhé!
