### ISSUE TITLE
Object detection faster RCNN

### ISSUE THREAD

**Issue by ThorPham** [dlapplications/dlapplications.github.io#18]
Em đang có vấn đề sau mong các đại ca gợi ý cách giải quyết 
Em đang có project là object detection trên tạp chí detection phone và shoe
tạp chí thì có nhiều object khác nhưng mà ta ko quan tâm như laptop,quần áo....
Bên em xài model object detection dùng faster RCNN với Inception-ResNet làm pretraining trên data image net. Cái model này đóng bounding box rất tốt đóng dc cả phone và shoe cả laptop, quần áo. Nhưng mà classifier nó classifier cả laptop và quần áo ( vì chỉ classifier phone với shoe nên nó sẽ classifier laptop một là ra phone 2 là ra shoe).
Em thì nghĩ rằng cái RPN trong faster dùng pretraining của image net nên nó sẽ proposal toàn bộ các object có trong image net. Nên em nghĩ sẽ training lại cái RPN chỉ training trên phone và shoe thôi.
Một số khác lại đưa ra giải pháp là dùng 1 threshold để loại đi các object như laptop ,quần áo để nó thành background.

**Comment by gachiemchiep** [comment]
@ThorPham Em ơi, lần tới viết question thì gọn gọn lại cho dễ hiểu nhé .

Ví dụ như câu hỏi của em lần này chỉ cần viết ngắn gọn là 

### Câu hỏi về object detection 

1. Input : ảnh tạp chí , ( thêm ví dụ về ảnh ) 
2. Output: bnbox + object của shoe , ví dụ về output 
3. Hiện tại : đang dùng cái gì? Train bằng cach nào nào ? Accuracy đạt bao nhiêu
4. Vấn đề : độ chính xác không đủ ,.... 
5. Phương án: nếu có thì em ghi vào đây, nếu không thì bỏ trống. 

Em thử ghi lại câu hỏi theo 5 mục ở trên rồi edit lại nhé.

**Comment by ThorPham** [comment]
Cảm ơn đại ca để em sửa lại 
1, Input : ảnh tạp chí ( gồm rất nhiều object shoe,phone,laptop,television... nhưng chỉ muốn detection shoe và phone).
2, output : bounding box + object của shoe và phone
3, Đang dùng model faster RCNN dùng pretraining ResNet + Inception trên data imageNet. 
4. Vấn đề : những object không muốn detection như laptop,television lại được bounding box + classifier
5, 
- Phương án traing lại từ đầu ko dùng pretraining
- Tìm thresold loại bỏ object có threshold thấp

**Comment by hitogen** [comment]
@ThorPham  a chưa hiểu vấn đề lắm, nếu e chỉ muốn show ra box của shoes với phone thì chỉ cần lấy kết quả của shoe với phone còn mask out hết mấy cái khác là được mà nhỉ?

**Comment by hitogen** [comment]
@ThorPham a chưa hiểu vấn đề lắm,  ý e là ko muốn model detect mấy cái khác ngoài phone với shoe để giảm thời gian tính toán hay sao? E giải thích thêm chỗ này hộ a với.

**Comment by gachiemchiep** [comment]
@ThorPham 

A thấy bước 4. Vấn đề có thể giải quyết dễ dàng bằng cách:

- Viết một filter để kết quả output ra chỉ giữ lại shoe và phone. 

Còn 2 phương án em nêu ra thì phương án 1 có rủi ro cao,  phương án 2 có vẻ không liên quan.

- Phương án traing lại từ đầu ko dùng pretraining : lượng data của em có đủ không. Nếu quá ít và chưa thử dùng bao giờ thì sẽ dễ dẫn tới kết quả không như mong muốn. 

- Tìm thresold loại bỏ object có score thấp : cái này a thấy không liên quan trực tiếp tới 4. Object không mong muốn (tivi, ...)  sẽ vẫn bị phát hiện với score cao nếu nó đúng, không thể dựa trên score để lọai ra được.

**Comment by ThorPham** [comment]
Để em ngâm cứu thêm chứ cái detection nó chưa tốt nữa. Cảm ơn mấy đại ca

**Comment by hitogen** [comment]
@ThorPham  nếu ok rồi thì Thor đóng issue luôn nhá.
