### ISSUE TITLE
Viết bài về tổng hợp các framework DeepLearning 

### ISSUE THREAD

**Issue by gachiemchiep** [dlapplications/dlapplications.github.io#2]
Hello @dlapplications/dl_ap

Bài tiếp theo sau : https://dlapplications.github.io/2018-06-02-ml-quick-guide/ 
sẽ là một bài sơ lược, so sánh các framework. Sau đấy cuối bài là 1 tutorial nhỏ
để cài đặt pytorch (dự định dùng để chạy demo cho những phần tiếp theo)

**Comment by gachiemchiep** [comment]
@dl-applications  @hitogen 

Review bài này nhé https://dlapplications.github.io/2018-06-13-dlframework/

**Comment by hitogen** [comment]
@gachiemchiep  E thấy trong só sánh có OpenMP support mà không thấy đề cập đến nó có tác dụng j ạ. E chưa xài caffe nên không biết nhưng tưởng caffe viết hoàn toàn bằng C++ mà sao trong  phần C++ điểm nó thấp thế ạ?

**Comment by hitogen** [comment]
Với lại e nghĩ đại ca đánh số các Header giống như phần mục lục cho dễ comment ạ

**Comment by gachiemchiep** [comment]
@hitogen 

OpenMp support thi khi minh export ra c++ header, trong do no se dung OpenMp de thuc thi luon. luc execute chuong trinh se nhanh hon.

Caffe minh phai them mot dong library, sau day compile moi chay duoc. Bon kia chi can extract header thoi.

"đánh số các Header giống như phần mục lục" : tuc la sao a khong hieu ?

**Comment by gachiemchiep** [comment]
Mot so link tham khao

https://www.openmp.org/wp-content/uploads/omp-hands-on-SC08.pdf

https://www.intel.com/content/dam/www/public/us/en/documents/presentation/performance-optimization-deep-learning-frameworks.pdf

**Comment by ducanh841988** [comment]
Bài viết hay và rất hữu ích.
Mình có vài comments:
+ Không biết có nên thêm một phần về mức độ phổ biến và so sánh tốc độ của các framework không? Cái này cũng sẽ ảnh hưởng đến quá trình phát triển ứng dụng. Nếu cộng đồng lớn thì nhiều support hơn.
+ Chúng ta cũng sẽ phải chọn 1 framework để cho các bài thực hành tiếp theo. Mình thì vote cho tensorflow vì có thể triển khai nhiều devices và cộng đồng lớn.

**Comment by hitogen** [comment]
@gachiemchiep đánh số header ý e là a ghi số trong phần mục lục mà xuống dưới các phần thì không đánh số nên hơi khó theo dõi ạ.

**Comment by hitogen** [comment]
@gachiemchiep  srr đại ca e gà mờ nên vẫn không hiểu sao openMP chỉ cần c++ header để chạy ạ? ko cần compile j cả ạ?

**Comment by gachiemchiep** [comment]
@hitogen .Phần đánh số thì a hiểu rồi.  Anh nói ngắn quá nó thành khó hiểu. Thực ra thì nó đơn giản như thế này thôi.

1. OpenMP là 1 library để paralleling quá trình tính toán, tương thích với các chip bên intel hay arm. Ví dụ chúng ta hay sử dụng Cuda với Gpu của Nvidia. Thì OpenMP cũng giống như Cuda thôi, nhưng khác là có thể chạy trên nhiều nền tảng khác nhau. 

2. C++ header là một file header để import bình thường thôi.  Chỉ cần có file này là có thể chạy load và chạy được model. Load thì chỉ một lần thì không sao, nhưng việc  chạy model này cũng phải được paralleling để chạy nhanh hơn. Thiết bị đầu cuối lại có nhiều nền tảng khác nhau.

3. Từ điểm 2 thì thấy được là vừa phải paralleling, vừa phải đáp ứng nhiều nền tảng khác nhau. Vậy thì phải lựa cái library support nhiều nền tảng nhất -> paralleling

**Comment by ducanh841988** [comment]
chỉnh bài chế độ hidden nhé. Mình sửa thử mà nó vẫn view bình thường.

**Comment by gachiemchiep** [comment]
@ducanh841988 

```
Không biết có nên thêm một phần về mức độ phổ biến và 
so sánh tốc độ của các framework không? 
Cái này cũng sẽ ảnh hưởng đến quá trình phát triển ứng dụng. 
Nếu cộng đồng lớn thì nhiều support hơn.
```
Cái này tôi thấy khó. Tùy quan điểm mỗi người thôi.

```
Chúng ta cũng sẽ phải chọn 1 framework để cho các bài thực hành tiếp theo. 
Mình thì vote cho tensorflow vì có thể triển khai nhiều devices và cộng đồng lớn.
```
Cái này phải để buổi meeting sau rồi bàn luôn.

**Comment by hitogen** [comment]
@gachiemchiep  e hiểu rồi ạ. Thanks đại ca.
Có nên thêm vào khả năng support training trên nhiều GPU k ạ?

**Comment by gachiemchiep** [comment]
@ducanh841988 @hitogen 

Đã update bài nhé

**Comment by hitogen** [comment]
@gachiemchiep phần về openMP thêm vào rất đáng tham khảo ạ. Thanks đại ca

**Comment by gachiemchiep** [comment]
@ducanh841988 @hitogen

Nếu không có reviews hay comment gì thêm sẽ đưa vào lịch post nhé

**Comment by ducanh841988** [comment]
OK. Cho bai nay len CN nhe.

**Comment by hitogen** [comment]
Ok ạ.

**Comment by gachiemchiep** [comment]
Đã schedule vào 20h ngày 21 tháng 6 (trước giờ đá banh 1 tiếng).
Issue này đóng ở đây.
