### ISSUE TITLE
[Thông báo] Một số thay đổi của thư mục _post

### ISSUE THREAD

**Issue by gachiemchiep** [dlapplications/dlapplications.github.io#20]
@dlapplications/dl_ap @nxthuan512 @HaiDang2001VN  @hitogen  @ducanh841988  @ThorPham 

Thông báo

## Thay đổi trong cấu trúc của thư mục _post 

Thư mục _post cũ ở dạng: 

```
_posts/
....................
│   ├── 2018-06-27-Brief-History-of-Deep-learning.md
│   ├── 2018-07-15-Transfer-Learning-Basic.md
...................
```

Đễ cho dễ sắp xếp hơn chia laị như sau

```
_posts/
├── dl_ap
│   ├── 2018-06-02-ml-quick-guide.md

├── dl_basic
│   ├── 2018-06-15-MLP.md

├── dl_news
└── tutorial
    
```

Chi tiết sẽ cập nhật tại wiki 

## Đề nghị 

Hiện nay team đã lâm vào tình trạng không có bài để post. Mọi người cũng đều bận và ít có thời gian cập nhật để viết bài. Các bài viết tiếp theo đều thuộc loại khó, tốn công và thời gian. Nên đề nghị bổ sung thêm một loạt bài về các news liên quan tới AI nói chung và Deep Learning nói riêng. 

Mọi người biểu quyết cho ý kiến nhé.
Nếu đồng ý với ý kiến này thì sẽ bàn chi tiết sau.

**Comment by hitogen** [comment]
@all Về phần bổ sung news chữa cháy như đại ca @gachiemchiep có nói e có ý kiến thế này, mỗi tuần e sẽ tạo một issue mới để mọi người vào comment link những cái mà mọi người đã đọc thấy hay trong tuần đó rồi cứ hết một tuần e tổng hợp lại để ra 1 cái dạng newsletter, vừa để chữa cháy vừa là nội dung mới cho page. Mọi người thấy sao ạ?

**Comment by gachiemchiep** [comment]
@hitogen 

A nghĩ cữ tạo một issue mới cho mỗi news.
Trong một tuần nếu không có ai nhận viết thì issue đó sẽ  bị đóng lại.  

@nxthuan512 @HaiDang2001VN @ducanh841988 @ThorPham 
Mọi người có trang web nào chuyên để lấy news thì post vào đây nhé. Sẽ tổng hợp lại trên wiki cho dễ dùng 

Lục trong các issue khác thì hiện tại tìm dc các link dưới đây 

https://machinelearningmastery.com/
http://www.wildml.com/deep-learning-glossary/
https://us13.campaign-archive.com/home/?u=67bd06787e84d73db24fb0aa5&id=6c9d98ff2c
http://aiweekly.co/
https://join.slack.com/t/toronto-ai/shared_invite/enQtMjE5NTM5MzY3NTU0LTQ0ZDIyM2ZlZDYwMmRjY2I2NTEyMjZjYzJkNzljZTI1ZWRiMDkzYjUyZjRkMTc5ZDM0OGJmZjdmNzM5NDM5Zjk

Cá nhân thì hiện tại thì tham gia reddit là chủ yếu 

https://www.reddit.com/r/MachineLearning/

**Comment by HaiDang2001VN** [comment]
Dạ em có một vài link sau:
[arXiv Sanity](http://www.arxiv-sanity.com/)
[DL-Weekly](https://www.deeplearningweekly.com/)
[DeepMind](https://deepmind.com/blog/)
Bình thường [Quora](https://www.quora.com/) có notice em mấy bài mới về Deep Learning, nhưng mỗi ngày một bài thôi, với lại [OpenAI](https://openai.com/) hay có mấy papers về Reinforcement Learning ạ.

**Comment by gachiemchiep** [comment]
@HaiDang2001VN Cám ơn em

**Comment by gachiemchiep** [comment]
Hiện tại không còn thảo luận nào nữa nên sẽ tạm đóng lại
