### ISSUE TITLE
Điền thông tin còn thiếu trong _config.yml

### ISSUE THREAD

**Issue by gachiemchiep** [dlapplications/dlapplications.github.io#4]
@hitogen ơi.

Còn mấy chỗ vẫn thiếu. Em tạo cái còn thiếu rồi điền vào nhé. 

```
# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Facebook App ID
# fb_app_id: ""
```

**Comment by hitogen** [comment]
cái này là điền cái vậy ạ đại ca @gachiemchiep

**Comment by gachiemchiep** [comment]
@hitogen 

Tài khoản Disqus để hiện chức năng comment

Tài khoản facebook để hiện thông tin facebook

**Comment by ducanh841988** [comment]
Để mình tạo cái này rồi gửi cho Tuấn

**Comment by hitogen** [comment]
@ducanh841988  đại ca tìm ra cái facebook app id chưa ạ?

**Comment by ducanh841988** [comment]
Đang bị bon fb chơi hay sao ấy. Tạo không được app từ facebook developer. @hitogen  cũng thử mà chưa được.

**Comment by gachiemchiep** [comment]
Close issue vì không active 3 tuần
