### ISSUE TITLE
Thống nhất tittle cho post

### ISSUE THREAD

**Issue by hitogen** [dlapplications/dlapplications.github.io#5]
@dl-applications  e nghĩ mình nên thống nhất lại cách đặt tittle cho các post, hiện nay thì đang có 2 cách đặt title trong blog. 
Một của a @gachiemchiep là title lớn là tên bài viết, titile nhỏ là tên series (ví dụ: Deep Learning Framework - Deep Learning và Ứng Dụng Phần 2.). 
Còn của e là title lớn là tên series, title nhỏ là tên bài viết (ví dụ: Deep learning cơ bản (phần 1) - Nền tảng của deep learning - Perceptron).
Theo các đại ca thì nên sửa như nào cho nhất quán ạ?

**Comment by gachiemchiep** [comment]
@hitogen 

A nghĩ cái nhỏ là để thuyết minh, làm rõ cái to. Mình đọc bài cũng bắt đầu từ đầu mục (chữ to) sau mới vào thân bài (chữ nhỏ). Cho nên để chữ to là tên bài, để chữ nhỏ thuyết minh thêm chữ to thuộc phần nào của series. Như vậy dễ hiểu hơn

**Comment by ducanh841988** [comment]
@hitogen 
A cũng đồng ý với cách của @gachiemchiep

**Comment by hitogen** [comment]
Vậy mình thống nhất cách đặt tên của a @gachiemchiep nhé . E sẽ sửa bài của e lại cho đồng bộ.
E xin đc close issue. Thanks mọi người
