### ISSUE TITLE
review cài đặt tensorflow cho môi trường ảo anaconda

### ISSUE THREAD

**Issue by ducanh841988** [dlapplications/dlapplications.github.io#6]
Dear all,
Please review my draft.
[ https://dlapplications.github.io/2018-06-18-install-TF-with-Anaconda](https://dlapplications.github.io/2018-06-18-install-TF-with-Anaconda)

Thank you
Duc Anh

**Comment by hitogen** [comment]
@ducanh841988  cái phần code đại ca nên format dùng ``` conda env list ``` như này cho nó dễ nhìn ạ.

**Comment by hitogen** [comment]
@ducanh841988  phần youtube video đại ca dùng cái này để embed thử xem ạ.
<iframe width="560" height="315" src="https://www.youtube.com/embed/dQw4w9WgXcQ" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

**Comment by ducanh841988** [comment]
a dùng cái iframe mà có vẻ ko hiện được video.

**Comment by hitogen** [comment]
A để sai link thôi ạ, phải để link embed chứ ko phải link trên address ạ.
E sửa lại với format lại mấy chỗ code, a kiểm tra lại ạ

**Comment by hitogen** [comment]
@ducanh841988  trong bài a thêm phần hướng dẫn cài với xài jupyter notebook được ko ạ?

**Comment by ducanh841988** [comment]
@hitogen @gachiemchiep them pytorch va jupyter. Moi nguoi xem lai. Neu ok thi cho len song tap tiep theo.

**Comment by hitogen** [comment]
@ducanh841988  đại ca cho mấy cái gạch đầu dòng thành in hoa hết được k ạ. 1 nửa in hoa 1 nửa viết thường nhìn nó ko đc đẹp.
Bài này có trong series nào không hay chỉ vậy thôi ạ?

**Comment by gachiemchiep** [comment]
Để tối về tôi sẽ review

**Comment by gachiemchiep** [comment]
@ducanh841988 

Đã review ở 30b5571ec005d645c590d62c4bb539bc64dd5487 nhé

**Comment by gachiemchiep** [comment]
@ducanh841988 

Sua xong chua ong.

**Comment by ducanh841988** [comment]
@gachiemchiep sua xong roi nhe! Minh cho len song luon roi! Sorry vi tre nen chua de check lai
