### ISSUE TITLE
Add button to join Forum

### ISSUE THREAD

**Issue by ducanh841988** [dlapplications/dlapplications.github.io#8]
đây là code để join forum. Nếu có thể để lên trang github thì hay.

<table border="0" width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse;"><tr style=""><td height="28" style="line-height:28px;">&nbsp;</td></tr><tr><td style=""><table border="0" width="280" cellspacing="0" cellpadding="0" style="border-collapse:separate;background-color:#ffffff;border:1px solid #dddfe2;border-radius:3px;font-family:Helvetica, Arial, sans-serif;margin:0px auto;"><tr style="padding-bottom: 8px;"><td style=""><img class="img" src="https://scontent-nrt1-1.xx.fbcdn.net/v/t1.0-9/c0.0.420.219/32807833_213662549230647_7894299586838134784_n.jpg?_nc_cat=0&amp;oh=45f67c3ed46e1e253877cee2c47b6bc6&amp;oe=5BBD2C06" width="280" height="146" alt="" /></td></tr><tr><td style="font-size:14px;font-weight:bold;padding:8px 8px 0px 8px;text-align:center;">Forum Deep learning và ứng dụng</td></tr><tr><td style="color:#90949c;font-size:12px;font-weight:normal;text-align:center;">Facebook group · 998 members</td></tr><tr><td style="padding:8px 12px 12px 12px;"><table border="0" cellspacing="0" cellpadding="0" style="border-collapse:collapse;width:100%;"><tr><td style="background-color:#4267b2;border-radius:3px;text-align:center;"><a style="color:#3b5998;text-decoration:none;cursor:pointer;width:100%;" href="https://www.facebook.com/plugins/group/join/popup/?group_id=1601966719912937&amp;source=email_campaign_plugin" target="_blank" rel="noopener"><table border="0" cellspacing="0" cellpadding="3" align="center" style="border-collapse:collapse;"><tr><td style="border-bottom:3px solid #4267b2;border-top:3px solid #4267b2;"><img width="16" src="https://facebook.com/images/groups/plugin/email/app_fb_32_fig_white.png" /></td><td style="border-bottom:3px solid #4267b2;border-top:3px solid #4267b2;color:#FFF;font-family:Helvetica, Arial, sans-serif;font-size:12px;font-weight:bold;">Join Group</td></tr></table></a></td></tr></table></td></tr><tr><td style="border-top:1px solid #dddfe2;font-size:12px;padding:8px 12px;">Forum của Deep Learning và ứng dụng để các bạn thảo luận và chia sẻ các thông tin liên quan đến học tập, kinh nghiệm làm việc với các mô hình Deep Lea...</td></tr></table></td></tr><tr style=""><td height="14" style="line-height:14px;">&nbsp;</td></tr></table>

**Comment by gachiemchiep** [comment]
@ducanh841988 

Cai nay thi de cho nao dc nhi ? chi con o ben duoi (link toi facebook, github ) la con cho thoi .  

![image](https://user-images.githubusercontent.com/2300329/41826288-3ff14f64-7863-11e8-8bc8-a4d73d23bb27.png)

**Comment by ducanh841988** [comment]
@gachiemchiep Thay cai link hien tai thanh cai nay nhe. https://www.facebook.com/Deep-learning-và-ứng-dụng-204704190126483

**Comment by gachiemchiep** [comment]
@ducanh841988 

Đã add ở fa84378aa30d70c614c8cd6e13c06f5cf078be9f

Hình như ở dưới đây. Không có icon tương tự nên lấy icon messager của facebook 

![image](https://user-images.githubusercontent.com/2300329/42458796-6c5ca6fc-83d5-11e8-9f85-65915634485b.png)

Nếu không vấn đề gì thì close nhé

**Comment by ducanh841988** [comment]
Cái chữ F link vào trang không khả dụng. @gachiemchiep  check lại dùm nhé

**Comment by gachiemchiep** [comment]
@ducanh841988 
Hiện đường link để chữ "Deep learning và ứng dụng" nên ấn vào hiện ra lỗi.
Cần phải thay bằng id của facebook.

Ông biết id không. đưa cho t để sửa.

**Comment by gachiemchiep** [comment]
Đã sửa. Close tại đây
